language: cpp
compiler: g++

before_install:
	- wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.5-18_amd64.deb
	- sudo dpkg -i cuda-repo-ubuntu1404_7.5-18_amd64.deb
	- sudo apt-get update
	- sudo apt-get install cuda-7-5

addons:
	apt:
		packages:
			- llvm

install:
	- mkdir build
	- cd build
	- cmake ../ 
	- make
